# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'oml-vagrant-dev-config.rb'
include MyVars

Vagrant.configure("2") do |config|

	config.vm.define "oml-wombat" do |app|
	app.vm.box = "centos-VAGRANTSLASH-7"
	app.vm.hostname = "oml-wombat.example.com"
	app.vm.network "public_network", ip: OMLWOMBAT-IP
	end

	config.vm.provision :ansible do |ansible|
	ansible.inventory_path = "inventory"
  	ansible.playbook = "main.yml"
	end

end
