# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.define "oml-pstn" do |app|
	app.vm.box = "debian/jessie64"
	app.vm.hostname = "oml-pstn.example.com"
	app.vm.network "public_network", ip: "192.168.43.47"
	end

	config.vm.provision :ansible do |ansible|
	ansible.inventory_path = "inventory"
  	ansible.playbook = "main.yml"
	end

end
