# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.define "asterisk" do |app|
	app.vm.box = "centos-VAGRANTSLASH-7"
	app.vm.hostname = "oml-asterisk.example.com"
#	app.vm.network "public_network", ip: "192.168.95.201"
	app.vm.network "private_network", ip: "192.168.200.201"
	end

end
