# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se instala este paquete necesario antes de hacer update
- name: Install apt-transport-https
  apt: name=apt-transport-https state=present
  become: true
  become_method: sudo

# Update/upgrade, https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name: Update/upgrade of system
  apt: "update_cache=yes cache_valid_time=12 upgrade=yes dpkg_options='force-confdef'"
  become: true
  become_method: sudo

  # Intalo los paquetes necesarios para la parte VoIP -- FIX ME -- separar paquetes de asterisk y paquetes de kamailio
- name: Installation of Asterisk
  apt: "name={{ item }} state=present"
  with_items:
    - asterisk
  become: true
  become_method: sudo

...
