# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "oml-kamailio" do |app|
  app.vm.box = "centos-VAGRANTSLASH-7"
  app.vm.hostname = "oml-kamailio.example.com"
  app.vm.network "public_network", ip: "192.168.43.46"
  end

end
